apiVersion: v1
kind: Namespace
metadata:
  name: zenstack

---
apiVersion: v1
kind: Secret
metadata:
  name: zenstack-secrets
  namespace: zenstack
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: "password"
  MINIO_ROOT_USER: "minioadmin"
  MINIO_ROOT_PASSWORD: "minioadmin"
  ZENML_SERVER_JWT_SECRET_KEY: "x09a@3sad*Df42ad566bb"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: zenstack-config
  namespace: zenstack
data:
  MYSQL_DATABASE: "zenml"
  MINIO_PORT: "9100"
  MINIO_CONSOLE_PORT: "9001"
  ZENML_PORT: "8080"
  MLFLOW_PORT: "5000"
  MLFLOW_BUCKET_NAME: "mlflowartifacts"
  ZENML_BUCKET_NAME: "zenmlartifacts"

#######################################
#              MYSQL
#######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: zenstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - name: mysql
          image: mysql:8.0
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: MYSQL_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: zenstack-config
                  key: MYSQL_DATABASE
          volumeMounts:
            - name: mysql-data
              mountPath: /var/lib/mysql
      volumes:
        - name: mysql-data
          hostPath:
            path: /microk8s/mysql-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: zenstack
spec:
  ports:
    - port: 3306
  selector:
    app: mysql

---
apiVersion: v1
kind: Service
metadata:
  name: mysql-nodeport
  namespace: zenstack
spec:
  type: NodePort
  selector:
    app: mysql
  ports:
    - name: mysql
      port: 3306
      nodePort: 30306

#######################################
#              MINIO
#######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: zenstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args: ["server", "/data", "--console-address", ":9001"]
          ports:
            - containerPort: 9100
            - containerPort: 9001
          env:
            - name: MINIO_ROOT_USER
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MINIO_ROOT_USER
            - name: MINIO_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MINIO_ROOT_PASSWORD
          volumeMounts:
            - name: minio-data
              mountPath: /data
          # readinessProbe:
          #   httpGet:
          #     path: /minio/health/live
          #     port: 9100
          #   initialDelaySeconds: 10
          #   periodSeconds: 20
      volumes:
        - name: minio-data
          hostPath:
            path: /microk8s/minio-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: minio
  namespace: zenstack
spec:
  type: ClusterIP
  ports:
    - name: api
      port: 9100
    - name: console
      port: 9001
  selector:
    app: minio

---
apiVersion: v1
kind: Service
metadata:
  name: minio-nodeport
  namespace: zenstack
spec:
  type: NodePort
  selector:
    app: minio
  ports:
    - name: api
      port: 9100
      nodePort: 30110
    - name: console
      port: 9001
      nodePort: 30091

#######################################
#              ZENML
#######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zenml
  namespace: zenstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zenml
  template:
    metadata:
      labels:
        app: zenml
    spec:
      containers:
        - name: zenml
          image: zenmldocker/zenml-server
          ports:
            - containerPort: 8080
          env:
            - name: MYSQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MYSQL_ROOT_PASSWORD
            - name: ZENML_STORE_URL
              value: "mysql://root:password@mysql/zenml"
            - name: ZENML_SERVER_JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: ZENML_SERVER_JWT_SECRET_KEY
            - name: AWS_ENDPOINT_URL
              value: http://minio:9100
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MINIO_ROOT_USER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: AWS_REGION
              value: us-east-1
            - name: MINIO_BUCKET
              valueFrom:
                configMapKeyRef:
                  name: zenstack-config
                  key: ZENML_BUCKET_NAME

---
apiVersion: v1
kind: Service
metadata:
  name: zenml
  namespace: zenstack
spec:
  type: ClusterIP
  ports:
    - port: 8080
  selector:
    app: zenml

---
apiVersion: v1
kind: Service
metadata:
  name: zenml-nodeport
  namespace: zenstack
spec:
  type: NodePort
  selector:
    app: zenml
  ports:
    - name: http
      port: 8080
      nodePort: 30080

#######################################
#              MLFLOW
#######################################
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mlflow
  namespace: zenstack
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mlflow
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
        - name: mlflow
          image: ghcr.io/mlflow/mlflow:latest
          command:
            - "mlflow"
            - "server"
            - "--host=0.0.0.0"
            - "--port=5000"
            - "--backend-store-uri=mysql+pymysql://root:password@mysql:3306/mlflow_db"
            - "--serve-artifacts"
            - "--artifacts-destination=s3://mlflow"
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MINIO_ROOT_USER
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: zenstack-secrets
                  key: MINIO_ROOT_PASSWORD
            - name: AWS_REGION
              value: "us-east-1"
            - name: MLFLOW_S3_ENDPOINT_URL
              value: "http://minio:9100"
          volumeMounts:
            - name: mlflow-data
              mountPath: /mlflow
          # readinessProbe:
          #   httpGet:
          #     path: /health
          #     port: 5000
          #   initialDelaySeconds: 20
          #   periodSeconds: 20
      volumes:
        - name: mlflow-data
          hostPath:
            path: /microk8s/mlflow-data
            type: DirectoryOrCreate

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow
  namespace: zenstack
spec:
  type: ClusterIP
  ports:
    - port: 5000
  selector:
    app: mlflow

---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-nodeport
  namespace: zenstack
spec:
  type: NodePort
  selector:
    app: mlflow
  ports:
    - name: http
      port: 5000
      nodePort: 30500
